# Script to create the JSON data for the Day 1 exercise
import json

survey_responses = [
    ["ChatGPT", "Claude"],
    ["ChatGPT"],
    ["Claude", "Gemini", "ChatGPT"],
    ["Copilot", "ChatGPT"],
    ["ChatGPT", "Grok"],
    ["Claude", "ChatGPT", "Gemini", "Copilot"],
    ["Gemini"],
    ["ChatGPT", "Claude", "Copilot"],
    ["Claude", "Grok"],
    ["ChatGPT", "Gemini"],
    ["Copilot"],
    ["ChatGPT", "Claude", "Gemini", "Copilot", "Grok"],
    ["Claude", "ChatGPT"],
    ["Gemini", "Grok"],
    ["ChatGPT"],
    ["Claude", "Copilot", "Gemini"],
    ["ChatGPT", "Grok"],
    ["Claude"],
    ["ChatGPT", "Copilot"],
    ["Gemini", "ChatGPT"],
    ["Claude", "Grok", "Gemini"],
    ["ChatGPT", "Copilot", "Claude"],
    ["Grok"],
    ["ChatGPT", "Gemini", "Grok"],
    ["Claude", "Copilot"],
    ["ChatGPT"],
    ["Gemini", "Claude", "ChatGPT", "Grok"],
    ["Copilot", "Grok"],
    ["ChatGPT", "Claude", "Gemini"],
    ["Claude", "Copilot", "Grok"],
    ["ChatGPT", "Gemini"],
    ["Grok", "Claude"],
    ["ChatGPT", "Copilot", "Gemini", "Grok"],
    ["Claude"],
    ["ChatGPT", "Grok", "Copilot"],
    ["Gemini", "Claude"],
    ["ChatGPT"],
    ["Claude", "Gemini", "Grok", "Copilot"],
    ["ChatGPT", "Claude"],
    ["Copilot", "Gemini"],
    ["ChatGPT", "Grok"],
    ["Claude", "ChatGPT", "Copilot"],
    ["Gemini"],
    ["ChatGPT", "Claude", "Gemini", "Grok"],
    ["Copilot"],
    ["ChatGPT", "Gemini", "Claude"],
    ["Grok", "Copilot", "Claude"],
    ["ChatGPT"],
    ["Claude", "Gemini"],
    ["ChatGPT", "Copilot", "Grok", "Claude", "Gemini"]
]

with open('survey_responses.json', 'w') as f:
    json.dump(survey_responses, f, indent=2)